name: publish ghcr app-habit-print

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'packages/app-habit-print/**'

env:
  IMAGE_NAME: app-habit-print
  REGISTRY: ghcr.io

jobs:
  publish_container:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set variables
        id: vars
        run: |
          cat <<EOF >> $GITHUB_OUTPUT
          CONTAINER_TAG="${{env.REGISTRY}}/${{github.actor}}/${{env.IMAGE_NAME}}:latest"
          EOF

      - name: Set up Docker Buildx (multi-platform builds)
        uses: docker/setup-buildx-action@v3

      - name: Build & push image
        run: |
          echo "${{secrets.GITHUB_TOKEN}}" | docker login ${{env.REGISTRY}} -u ${{github.actor}} --password-stdin
          docker buildx build ./packages/${{env.IMAGE_NAME}} \
            --push \
            --platform linux/amd64,linux/arm64 \
            --file ./packages/${{env.IMAGE_NAME}}/Dockerfile.prod \
            --tag ${{steps.vars.outputs.CONTAINER_TAG}}
